import PDFDocument from 'pdfkit';
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx';
import { IVideo } from '../models/Video';
import { ISummary } from '../models/Summary';
import { IQuestion } from '../models/Question';
import { IClarification } from '../models/Clarification';

export async function generatePDFReport(video: IVideo, summaries: ISummary[], questions: IQuestion[], clarifications: IClarification[]): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument();
        const buffers: Buffer[] = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));

        // Header
        doc.fontSize(20).text(`YouTube Tutor Report: ${video.title}`, { align: 'center' });
        doc.moveDown();

        // Summaries
        doc.fontSize(16).text('Summaries');
        summaries.forEach(s => {
            doc.fontSize(14).text(`${s.level.charAt(0).toUpperCase() + s.level.slice(1)} Summary:`);
            doc.fontSize(12).text(s.content);
            doc.moveDown();
        });

        // Topics
        doc.fontSize(16).text('Topics & Timestamps');
        video.topics.forEach(t => {
            doc.fontSize(12).text(`${t.topic} (${t.start}s - ${t.end}s): ${t.keyInsight}`);
        });
        doc.moveDown();

        // Questions
        doc.fontSize(16).text('Self-Assessment Questions');
        questions.forEach((q, i) => {
            doc.fontSize(12).text(`${i + 1}. [${q.type}] ${q.text}`);
            if (q.options) {
                q.options.forEach((opt, idx) => doc.text(`   ${String.fromCharCode(65 + idx)}) ${opt}`));
            }
            doc.moveDown();
        });

        // Clarifications
        if (clarifications && clarifications.length > 0) {
            doc.fontSize(16).text('Concept Clarifications');
            clarifications.forEach((c, i) => {
                doc.fontSize(12).text(`${i + 1}. Term: ${c.transcriptSnippet}`);
                doc.fontSize(10).text(`Reason: ${c.reason}`, { oblique: true });
                doc.fontSize(12).text(`Explanation: ${c.clarificationText}`);
                if (c.examples && c.examples.length > 0) {
                    doc.fontSize(10).text(`Examples: ${c.examples.join(', ')}`);
                }
                doc.moveDown();
            });
        }

        doc.end();
    });
}

export async function generateDocxReport(video: IVideo, summaries: ISummary[], questions: IQuestion[], clarifications: IClarification[]): Promise<Buffer> {
    const doc = new Document({
        sections: [{
            properties: {},
            children: [
                new Paragraph({
                    text: `YouTube Tutor Report: ${video.title}`,
                    heading: HeadingLevel.HEADING_1,
                }),
                new Paragraph({
                    children: [new TextRun({ text: "Generated by YouTube Tutor AI", italics: true })],
                }),
                ...summaries.map(s => ([
                    new Paragraph({ text: `${s.level.charAt(0).toUpperCase() + s.level.slice(1)} Summary`, heading: HeadingLevel.HEADING_2 }),
                    new Paragraph({ text: s.content })
                ])).flat(),

                new Paragraph({ text: "Topics", heading: HeadingLevel.HEADING_2 }),
                ...video.topics.map(t => new Paragraph({ text: `• ${t.topic} (${t.start}s): ${t.keyInsight}` })),

                new Paragraph({ text: "Questions", heading: HeadingLevel.HEADING_2 }),
                ...questions.map((q, i) => ([
                    new Paragraph({ text: `${i + 1}. ${q.text}` }),
                    ...(q.options ? q.options.map((opt, idx) => new Paragraph({ text: `   ${String.fromCharCode(65 + idx)}) ${opt}` })) : [])
                ])).flat(),

                new Paragraph({ text: "Clarifications", heading: HeadingLevel.HEADING_2 }),
                ...clarifications.map((c, i) => ([
                    new Paragraph({ text: `${i + 1}. ${c.transcriptSnippet}`, heading: HeadingLevel.HEADING_3 }),
                    new Paragraph({ text: `Explanation: ${c.clarificationText}` }),
                    ...(c.examples && c.examples.length > 0 ? [new Paragraph({ text: `Examples: ${c.examples.join(', ')}`, italics: true })] : [])
                ])).flat(),
            ],
        }],
    });

    return await Packer.toBuffer(doc);
}
